services:
  client:
    build: ./client
    depends_on:
      - server
    ports:
      - 3000:80
  server:
    build: ./server
    ports:
      - 3001:3001
    volumes:
      - kiruna-uploads:/app/uploads
volumes:
    kiruna-uploads: